name: finaces-app

services:
  mailpit:
    image: axllent/mailpit
    restart: always
    volumes: 
      - mailpit_data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 100
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - openledger_hub-network

  backend:
    build:
      context: ./
      target: backend
    restart: always
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
      - "5555:5555"
    environment:
      PORT: ${BACKEND_PORT}
      JWT_SECRET: ${BACKEND_JWT_SECRET}
      DATABASE_URL: file:/usr/local/app/data/sqlite.db
      FRONTEND_URL: ${BACKEND_FRONTEND_URL}
      RESEND_API_KEY: ${BACKEND_RESEND_API_KEY}
    depends_on:
      - mailpit
    volumes:
      - uploads:/usr/local/app/uploads
      - sqlite_data:/usr/local/app/data
    develop:
      watch:
        - path: ./backend/src
          action: sync
          target: /usr/local/app/src
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/prisma/
          action: rebuild
        - path: ./Dockerfile
          action: rebuild
    networks:
      - openledger_hub-network
  
  frontend:
    build:
      context: ./
      target: frontend
      args:
       - FRONTEND_BACKEND_URL=${FRONTEND_BACKEND_URL}
    restart: always
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT_CONTAINER}"
    environment:
      PORT: ${FRONTEND_PORT}
      PUBLIC_BACKEND_URL: ${FRONTEND_BACKEND_URL}
    depends_on:
      - backend
    develop:
      watch:
        - path: ./frontend/src
          action: sync
          target: /usr/local/app/src
        - path: ./frontend/public
          action: sync
          target: /usr/local/app/public
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/tsconfig.json
          action: rebuild
        - path: ./frontend/astro.config.mjs
          action: rebuild

networks:
  openledger_hub-network:
    driver: bridge

volumes:
  mailpit_data:
  uploads:
  sqlite_data: