FROM node:22-alpine AS base
WORKDIR /usr/local/app

FROM base AS backend
COPY backend/. ./
RUN mkdir -p /usr/local/app/uploads
RUN npm install
RUN npm run build
CMD ["sh", "-c", "npx prisma migrate deploy && npm run start"]

FROM base AS frontend
COPY frontend/. ./
RUN npm install
RUN npm run build